<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYhqz3lo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYhqz3lo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYhqz3lo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYhqz3lo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYhqz3lo\appProdProjectContainer([
    'container.build_hash' => 'Yhqz3lo',
    'container.build_id' => '0d0d8711',
    'container.build_time' => 1588134286,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYhqz3lo');
